import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { QueryProvider } from "@/components/provider/query-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import {
  Cursor,
  CursorFollow,
  CursorProvider
} from "@/components/animate-ui/components/animate/cursor";

const font = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "MaliSystem Admin dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        <CursorProvider>
          <QueryProvider>
            <Toaster richColors position="top-center" />
            {children}
          </QueryProvider>
          <Cursor />
          <CursorFollow>rhpaie</CursorFollow>
        </CursorProvider>
      </body>
    </html>
  );
}
